name: CI
#
on:
  push:
    branches: [ main ]

jobs:

  build_docker_frontend:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:frontend -f ./frontend/Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:frontend

  send:
      runs-on: ubuntu-latest

      steps:
          # Передаем файлы на сервер
        - name: Send file on server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATEKEY }}
            source: "./.github/workflows/docker-compose.yml"
            target: "~/hakaton"

  deploy:
    needs: [ build_docker_frontend, send ]
    runs-on: ubuntu-latest

    steps:
      - name: Run frontend deploy
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd ./hakaton/.github/workflows
            sudo docker-compose down service_frontend
            sudo docker-compose pull
            sudo docker-compose up --build -d service_frontend
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}

#      - name: Run mle worker deploy (upload data 2 mongo)
#        uses: appleboy/ssh-action@master
#        with:
#          script: |
#            cd ./stock-news/.github/workflows
#            sudo docker-compose down worker_mle
#            sudo docker-compose pull
#            sudo docker-compose up --build -d worker_mle
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.PRIVATEKEY }}